<a href="https://colab.research.google.com/github/mustafabozkaya/LLM-Bootcamp/blob/main/Module1/Quickstart%20guide%20to%20PyTorch%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quickstart guide to PyTorch Basics

LLM Bootcamp requires you to have PyTorch basics. In this Notebook, we have attached a Quickstart guide to get started with PyTorch along with important resources to get started with PyTorch.

##⚡️LLM Bootcamp
Before proceeding with the further modules, we expect you to atleast have basic knowledge of PyTorch. This notebook is a Quickstart guide for PyTorch Basics

If you are comfortable with PyTorch you can skip this notebook.

**Get Started with PyTorch**

An open source machine learning framework that accelerates the path from research prototyping to production deployment.

<code>pip install torch<code\>

**Table of Contents:**

- Basics

- Tensor Operations

- Extra PyTorch operations based on Tensor Shape

- Ouickstart- Build A Neural Network

In [ ]:
import torch
import numpy as np

### Basics
Just like Tensorflow, we shall continue playing with Tensors in PyTorch as well.

In [ ]:

#Create Tensor From Data(List)
data = [[1, 2],[3, 4]]
tensors = torch.tensor(data)
tensors

tensor([[1, 2],
        [3, 4]])

In [5]:
#Create from NumPy
np_array = np.arange(10)
tensor_np = torch.from_numpy(np_array)
tensor_np

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Shape, ndim and dtype
This is same as we saw in Numpy Tutorial - Day 1

In [8]:


tensor_np.shape

torch.Size([10])

In [7]:

tensor_np.ndim

1

In [9]:
tensor_np.dtype

torch.int64

### Tensor_Operations

In [10]:

ten1 = torch.tensor([1,2,3])
ten2 = torch.tensor([4,5,6])
ten1+ten2

tensor([5, 7, 9])

In [11]:
#You can either use + or torch.add to perform Tensor Additions

torch.add(ten1,ten2)

tensor([5, 7, 9])

In [12]:

torch.sub(ten2,ten1)

tensor([3, 3, 3])

In [13]:

torch.subtract(ten2,ten1)

#You can either use - or torch.sub to perform Tensor Additions

tensor([3, 3, 3])

In [14]:
ten1 - ten2

tensor([-3, -3, -3])

In [15]:
ten1 * 10

tensor([10, 20, 30])

In [20]:
ten1 **3

tensor([ 1,  8, 27])

In [18]:
ten1 /2

tensor([0.5000, 1.0000, 1.5000])

In [17]:
ten1 // 2

tensor([0, 1, 1])

In [19]:
ten1 %2

tensor([1, 0, 1])

#### Matrix Multiplication

**very important operation in Deep Learning- Matrix Multiplication**
- Rules of Matrix Multiplication:


(3,2) * (3,2) = Error

(4,3) * (3,2) = (4,2)

(2,2) * (2,5) = (2,5)

In [21]:
torch.matmul(ten1,ten2)

tensor(32)

In [23]:
matrix4_3 = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
matrix4_3.shape

torch.Size([4, 3])

In [24]:
matrix3_2 = torch.tensor([[1,2], [3,4], [5,6]])
matrix3_2.shape

torch.Size([3, 2])

In [25]:
result = torch.matmul(matrix4_3,matrix3_2) #=> will result in (4,2)
result

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100],
        [103, 136]])

In [26]:
result.shape

torch.Size([4, 2])

In [28]:
#You can also use torch.mm() which is a short for torch.matmul()

torch.mm(matrix4_3,matrix3_2)

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100],
        [103, 136]])


#### Transpose of tensor

In [29]:
matrix4_3

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [30]:
matrix4_3.T

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

In [31]:
torch.t(matrix4_3)

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])


### Extra_PyTorch_operations_based_on_Tensor_Shape
- Zeros
- Ones
- Random
- Full

In [32]:
tensorZeroes = torch.zeros((3,3))
tensorZeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [33]:
tensorOnes = torch.ones((3,3))
tensorOnes

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
tensorRandomN = torch.randn((3,3)) #includes negative tensors
tensorRandomN

tensor([[ 0.4039, -1.1849, -0.0229],
        [ 1.9324, -1.4725,  0.2451],
        [-1.7195,  1.8954,  0.0517]])

In [35]:
tensorRandom = torch.rand((3,3)) #includes only positive tensors
tensorRandom

tensor([[0.0737, 0.7743, 0.8502],
        [0.4037, 0.4170, 0.0665],
        [0.5384, 0.3786, 0.1458]])

In [36]:


customFill = torch.full((3,3),5)
customFill

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [37]:

initialFill = torch.full((3,3),0.01)
initialFill

tensor([[0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100]])

###Quickstart
#####Install **Torchvision**, The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.

In [39]:

pip install torchvision --no-deps

In [40]:
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
from torch import nn

In [41]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
root="data",
train=True,
download=True,
transform=ToTensor(),
)

100%|██████████| 26421880/26421880 [00:02<00:00, 12395433.39it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 210992.67it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3944607.71it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 17742216.10it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [43]:
type(training_data)

torchvision.datasets.mnist.FashionMNIST

In [45]:
train_data[0]

NameError: ignored

In [42]:
# Download test data from open datasets.
test_data = datasets.FashionMNIST(
root="data",
train=False,
download=True,
transform=ToTensor(),
)